import * as THREE from './three.module.js?v=4.0.0';
import {ITEMS,validStack} from './items.js?v=4.1.1';
import {createProp,propMaterial,updatePropMaterial} from './props.js?v=4.1.1';
import {WorldLighting,LAMP_TEMPERATURES} from './world-lighting.js?v=4.1.1';
import {placement} from './build-placement.js?v=4.1.1';
import {entityBoxes,boxesOverlap,orientedBox,rayBox} from './spatial.js?v=4.1.1';
import {BuildIndex,BuildBatches} from './build-acceleration.js?v=4.1.1';
const V=(x=0,y=0,z=0)=>new THREE.Vector3(x,y,z),clone=x=>JSON.parse(JSON.stringify(x));
const CEILING_OFFSETS=[[0,0],[-.15,0],[.15,0],[0,-.15],[0,.15]];
export class BuildWorld{
 constructor(scene,terrain,lunar=false){
  this.scene=scene;this.terrain=terrain;this.lunar=lunar;this.gravity=lunar?1.62:9.80665;this.entities=[];this.revision=0;this.drops=[];this.meshes=[];this.history=[];this.future=[];this.dirty=false;this.lightingDirty=true;this.lights=new WorldLighting();this.material=propMaterial(lunar);this.ghostMaterial=propMaterial(lunar,true);this.lights.attach(this.material.uniforms);
  this.spatialRevision=0;this.spatialOrder=0;this.index=new BuildIndex();this.lamps=new Set();this.batchMaterial=propMaterial(lunar,false,true);this.batchMaterial.uniforms=this.material.uniforms;this.batches=new BuildBatches(scene,this.batchMaterial);
  this.ray=new THREE.Raycaster();this.ray.far=16;this._v=V();this._n=V();this._q=new THREE.Quaternion();this._p=V();this._bounds=new THREE.Box3();this._near=[];
  this._support=V();this._down=V(0,-1,0);this._collision=V();this._ceiling=V();this._up=V(0,1,0);this._maskP=V();this._dropBefore=V();this._axisDistances=new Float64Array(3);this._axisExtents=new Float64Array(3);
  this.maskOrigin=new THREE.Vector2(1e6,1e6);this.maskData=new Uint8Array(512*512);this.mask=new THREE.DataTexture(this.maskData,512,512,THREE.RedFormat);this.mask.minFilter=this.mask.magFilter=THREE.NearestFilter;this.mask.generateMipmaps=false;this.maskDirty=true;
  this.storageKey='sky-expedition-world-'+(lunar?'moon':'earth')+'-v1';this.restore();
 }
 ground(x,z){return this.terrain.heightAt?.(x,z)||0;}
 snapshot(){return this.entities.map(e=>({uid:e.uid,id:e.id,position:e.position.toArray(),rotation:e.rotation.toArray().slice(0,3),params:clone(e.params)}));}
 save(){try{localStorage.setItem(this.storageKey,JSON.stringify({version:1,objects:this.snapshot(),drops:this.drops.map(d=>({stack:d.stack,position:d.mesh.position.toArray(),velocity:d.velocity.toArray(),age:d.age}))}));this.dirty=false;return true;}catch{return false;}}
 restore(){try{const data=JSON.parse(localStorage.getItem(this.storageKey));if(data)this.load(data);}catch{}}
 load(data){if(!data||!Array.isArray(data.objects))throw Error('Base no válida');for(const e of [...this.entities])this.remove(e.uid,false);for(const d of this.drops){this.scene.remove(d.mesh);if(d.mesh.geometry.userData.owned)d.mesh.geometry.dispose();}this.drops=[];
  for(const o of data.objects){if(!ITEMS[o.id]||ITEMS[o.id].tool||ITEMS[o.id].sample||!Array.isArray(o.position)||o.position.length!==3||!o.position.every(Number.isFinite)||Math.hypot(o.position[0],o.position[2])>605)continue;const r=Array.isArray(o.rotation)&&o.rotation.length===3&&o.rotation.every(Number.isFinite)?o.rotation.map(a=>a%(Math.PI*2)):[0,0,0];this.add(o.id,V(...o.position),new THREE.Euler(...r),o.id==='foundation'?{width:6,depth:6,...(o.params||{})}:o.id==='ramp-adaptive'?{rails:(Number(o.params?.rise)||1)>.65,...(o.params||{})}:o.params||{},o.uid,false);}
  for(const d of data.drops||[])if(ITEMS[d.stack?.id]&&Number.isInteger(d.stack.qty)&&d.stack.qty>0&&d.stack.qty<=30&&Array.isArray(d.position)&&d.position.length===3&&d.position.every(Number.isFinite)&&Math.hypot(d.position[0],d.position[2])<610)this.spawnDrop(d.stack,V(...d.position),Array.isArray(d.velocity)&&d.velocity.length===3&&d.velocity.every(Number.isFinite)?V(...d.velocity):V(),d.age||2);
  this.history=[];this.future=[];this.dirty=false;
 }
 checkpoint(inventory){this.history.push({objects:this.snapshot()});if(this.history.length>50)this.history.shift();this.future=[];}
 undo(inventory,redo=false){const source=redo?this.future:this.history,dest=redo?this.history:this.future;if(!source.length)return false;const previous=source[source.length-1],current=this.snapshot(),oldIds=new Set(previous.objects.map(o=>o.uid)),newIds=new Set(current.map(o=>o.uid)),delta=new Map();for(const o of current)if(!oldIds.has(o.uid))delta.set(o.id,(delta.get(o.id)||0)+1);for(const o of previous.objects)if(!newIds.has(o.uid))delta.set(o.id,(delta.get(o.id)||0)-1);
  // Build a temporary inventory transaction before mutating the scene.
  const slots=inventory.snapshot();for(const [id,amount] of delta)if(amount<0){let left=-amount;for(const slot of slots)if(slot?.id===id){const n=Math.min(left,slot.qty);slot.qty-=n;left-=n;}if(left)return false;}for(let i=0;i<slots.length;i++)if(slots[i]?.qty===0)slots[i]=null;
  for(const [id,amount] of delta)if(amount>0){let left=amount;for(const slot of slots)if(slot?.id===id){const n=Math.min(30-slot.qty,left);slot.qty+=n;left-=n;}for(let i=0;i<slots.length&&left;i++)if(!slots[i]){const n=Math.min(30,left);slots[i]={id,qty:n};left-=n;}if(left)return false;}
  source.pop();const next={objects:current},h=this.history,f=this.future;const currentById=new Map(current.map(o=>[o.uid,o]));this.load({objects:previous.objects.map(o=>currentById.get(o.uid)||o),drops:this.drops.map(d=>({stack:d.stack,position:d.mesh.position.toArray(),velocity:d.velocity.toArray(),age:d.age}))});this.history=h;this.future=f;dest.push(next);inventory.restore(slots);this.dirty=true;this.save();return true;}

 add(id,position,rotation=new THREE.Euler(),params={},uid=null,save=true){const item=ITEMS[id];if(!item)return null;params={...params};if(item.adaptive){params.width=Math.max(1,Math.min(24,Number(params.width)||item.size[0]));params.rails=params.rails??(id!=='ramp-adaptive-open'&&id!=='ramp-adaptive-wide');params.run=Math.max(.5,Math.min(48,Number(params.run)||4));params.rise=Math.max(.05,Math.min(30,Number(params.rise)||1));params.profile=Array.from({length:25},(_,i)=>Number.isFinite(Number(params.profile?.[i]))?Math.max(-260,Math.min(30,Number(params.profile[i]))):-.06);}params.temperature=Math.max(0,Math.min(2,Math.round(Number(params.temperature)||0)));if(params.storage)params.storage=Array.from({length:10},(_,i)=>validStack(params.storage[i]));if(params.name!==undefined)params.name=String(params.name).slice(0,32);if(params.pitch!==undefined)params.pitch=Math.max(-1.45,Math.min(1.5,Number(params.pitch)||0));if(item.kind==='foundation'){params.width=Math.max(2,Math.min(24,Math.round((Number(params.width)||8)/2)*2));params.depth=Math.max(2,Math.min(24,Math.round((Number(params.depth)||8)/2)*2));if(!Number.isFinite(params.fill))params.fill=1;params.fill=Math.max(.3,Math.min(260,params.fill));}
  const mesh=createProp(id,this.material,params);mesh.position.copy(position);mesh.rotation.copy(rotation);mesh.updateMatrixWorld(true);const e={uid:uid||'o-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8),id,item,position:mesh.position,rotation:mesh.rotation,params,mesh,anchor:V(),boxes:[]};mesh.userData.entity=e;e.spatialOrder=this.spatialOrder++;this.scene.add(mesh);this.entities.push(e);this.meshes.push(mesh);this.revision++;
  this.refresh(e);mesh.matrixAutoUpdate=false;if(item.category==='Iluminación')this.lamps.add(e);if(item.category==='Iluminación'){mesh.material=propMaterial(this.lunar);mesh.material.uniforms={...this.material.uniforms,lampOn:{value:e.params.on===false?0:1},lampColor:{value:new THREE.Color(LAMP_TEMPERATURES[e.params.temperature||0].color)}};}
  this.maskDirty=this.lightingDirty=true;if(save){this.dirty=true;this.save();}return e;
 }
 refresh(e){e.mesh.updateMatrix();e.mesh.matrixWorldAutoUpdate=true;e.mesh.updateMatrixWorld(true);e.mesh.matrixWorldAutoUpdate=false;e.colliders=entityBoxes(e.mesh.geometry,e.mesh.matrixWorld);e.boxes=e.colliders.map(b=>b.bounds);e.inverse=e.mesh.matrixWorld.clone().invert();e.bounds=e.mesh.geometry.boundingBox.clone().applyMatrix4(e.mesh.matrixWorld);this.index.add(e);this.spatialRevision++;this.maskDirty=this.lightingDirty=true;e.anchor.set(0,Math.min(e.item.size[1]+.2,1.6),0).applyMatrix4(e.mesh.matrixWorld);if(e.item.category==='Iluminación')e.anchor.set(0,e.item.kind==='ceiling-lamp'?-.18:e.item.kind==='lamp'?1.69:e.item.size[1]/2,e.item.kind==='wall-lamp'?.19:0).applyMatrix4(e.mesh.matrixWorld);}
 remove(uid,save=true){const i=this.entities.findIndex(e=>e.uid===uid);if(i<0)return;const e=this.entities[i];this.revision++;this.spatialRevision++;this.index.remove(e);this.lamps.delete(e);if(e.mesh.material!==this.material)e.mesh.material.dispose();e.mesh.removeFromParent();this.entities.splice(i,1);this.meshes.splice(this.meshes.indexOf(e.mesh),1);if(e.mesh.geometry.userData.owned)e.mesh.geometry.dispose();this.maskDirty=this.lightingDirty=true;if(save){this.dirty=true;this.save();}}
 change(e,params){Object.assign(e.params,params);if(e.item.category==='Iluminación'){e.mesh.material.uniforms.lampOn.value=e.params.on===false?0:1;e.mesh.material.uniforms.lampColor.value.set(LAMP_TEMPERATURES[e.params.temperature||0].color);}this.revision++;this.lightingDirty=true;this.dirty=true;this.save();}
 support(x,z,foot=Infinity){let height=this.ground(x,z);for(const e of this.index.query(x,z)){if(e.bounds.max.x<x||e.bounds.min.x>x||e.bounds.max.z<z||e.bounds.min.z>z)continue;
  if(e.item.kind==='ramp'&&Math.abs(e.rotation.x)+Math.abs(e.rotation.z)<.001){const p=this._support.set(x,0,z).applyMatrix4(e.inverse),run=e.params.run||e.item.size[2],rise=e.params.rise||e.item.size[1];if(Math.abs(p.x)<=(e.params.width||e.item.size[0])/2&&Math.abs(p.z)<=run/2){const y=e.position.y+rise*(.5-p.z/run);if(y<=foot+.30)height=Math.max(height,y);}continue;}
  const origin=this._support.set(x,Math.min(e.bounds.max.y+.01,foot+.301),z),down=this._down;for(const box of e.colliders){const t=rayBox(origin,down,box,Math.max(0,origin.y-height));if(t!==null&&t>.00001)height=Math.max(height,origin.y-t);}
 }return height;}
 collide(pos,previous,radius=.22,height=1.68){const floor=pos.y-height;for(const e of this.index.query(pos.x,pos.z,radius)){if(pos.x<e.bounds.min.x-radius||pos.x>e.bounds.max.x+radius||pos.z<e.bounds.min.z-radius||pos.z>e.bounds.max.z+radius)continue;
  let onRamp=false;if(e.item.kind==='ramp'&&Math.abs(e.rotation.x)+Math.abs(e.rotation.z)<.001){const p=this._collision.set(pos.x,0,pos.z).applyMatrix4(e.inverse),run=e.params.run||e.item.size[2],rise=e.params.rise||e.item.size[1],y=e.position.y+rise*(.5-p.z/run);onRamp=y<=floor+.30;}
  for(const box of e.colliders){if(onRamp&&!box.rail)continue;if(box.bounds.max.y<=floor+.26||box.bounds.min.y>=pos.y-.06)continue;
   // Upright oriented boxes use the same local slab for walking and placement.
   // Tilted props use narrow vertical samples, avoiding their empty AABB corners.
   const low=Math.max(floor+.27,box.bounds.min.y+.001),high=Math.min(pos.y-.06,box.bounds.max.y-.001);if(low>high)continue;
   for(let sample=0;sample<3;sample++){const y=sample===0?low:sample===1?(low+high)/2:high,delta=this._collision.set(pos.x,y,pos.z).sub(box.center),q=this._axisDistances,extent=this._axisExtents;let overlaps=true;for(let i=0;i<3;i++){const a=box.axes[i];q[i]=delta.dot(a);extent[i]=radius*Math.hypot(a.x,a.z);if(Math.abs(q[i])>=box.half.getComponent(i)+extent[i])overlaps=false;}if(!overlaps)continue;
    let axis=-1,push=Infinity,sign=1;for(let i=0;i<3;i++){const a=box.axes[i],horizontal=Math.hypot(a.x,a.z);if(horizontal<.25)continue;const depth=(box.half.getComponent(i)+extent[i]-Math.abs(q[i]))/horizontal;if(depth<push){push=depth;axis=i;sign=Math.sign(q[i])||1;}}
    if(axis>=0){const a=box.axes[axis],len=Math.hypot(a.x,a.z);pos.x+=a.x/len*push*sign;pos.z+=a.z/len*push*sign;}break;
   }
  }
 }return pos;}
 ceiling(x,z,foot){let ceiling=Infinity;const origin=this._ceiling,up=this._up;for(const e of this.index.query(x,z,.15)){if(x<e.bounds.min.x-.15||x>e.bounds.max.x+.15||z<e.bounds.min.z-.15||z>e.bounds.max.z+.15||e.bounds.max.y<foot+.3)continue;for(const [dx,dz] of CEILING_OFFSETS){origin.set(x+dx,foot+.3,z+dz);for(const box of e.colliders){const t=rayBox(origin,up,box,ceiling-origin.y);if(t!==null&&t>.001)ceiling=Math.min(ceiling,origin.y+t);}}}return ceiling;}
 raycast(origin,direction,max=16){this.ray.set(origin,direction);this.ray.far=max;const hits=this.ray.intersectObjects(this.index.raycast(origin,direction,max,this.ray.ray),false);let hit=hits.find(h=>h.object.visible);let ground=null,previous=0;if(!this.lunar){const t=direction.y<-.0000001?-origin.y/direction.y:Infinity;if(t>=.05&&t<=max)ground={distance:t,point:origin.clone().addScaledVector(direction,t),normal:V(0,1,0),entity:null};}else for(let t=.05;t<=max;t+=Math.max(.18,t*.018)){this._v.copy(direction).multiplyScalar(t).add(origin);if(this._v.y<=this.ground(this._v.x,this._v.z)){let lo=previous,hi=t;for(let i=0;i<9;i++){const mid=(lo+hi)/2;this._v.copy(direction).multiplyScalar(mid).add(origin);if(this._v.y>this.ground(this._v.x,this._v.z))lo=mid;else hi=mid;}const point=origin.clone().addScaledVector(direction,hi);ground={distance:hi,point,normal:V(0,1,0),entity:null};break;}previous=t;}
  if(hit&&(!ground||hit.distance<ground.distance)){const normal=hit.face.normal.clone().transformDirection(hit.object.matrixWorld);return {distance:hit.distance,point:hit.point,normal,entity:hit.object.userData.entity};}return ground;
 }
 foundationAt(x,z){return this.entities.find(e=>{if(e.id!=='foundation')return false;const p=V(x,e.position.y,z).applyMatrix4(e.inverse);return Math.abs(p.x)<=(e.params.width||6)/2+.11&&Math.abs(p.z)<=(e.params.depth||6)/2+.11;});}
 foundationParams(pos,rotation,width,depth){let high=-Infinity,low=Infinity;const c=Math.cos(rotation.y),s=Math.sin(rotation.y);for(let z=-depth/2;z<=depth/2+.01;z+=.5)for(let x=-width/2;x<=width/2+.01;x+=.5){const h=this.ground(pos.x+c*x+s*z,pos.z-s*x+c*z);high=Math.max(high,h);low=Math.min(low,h);}pos.y=high+.22;return {width,depth,fill:high-low+.47};}
 snapFoundation(position,rotation,width,depth,hit){let best=null,bestScore=Infinity;for(const e of this.entities){if(e.id!=='foundation')continue;const p=position.clone().sub(e.position).applyAxisAngle(V(0,1,0),-e.rotation.y),a=rotation.y-e.rotation.y,hx=(width*Math.abs(Math.cos(a))+depth*Math.abs(Math.sin(a)))/2,hz=(width*Math.abs(Math.sin(a))+depth*Math.abs(Math.cos(a)))/2,w=e.params.width||6,d=e.params.depth||6;if(Math.abs(p.x)>w/2+hx+1||Math.abs(p.z)>d/2+hz+1)continue;
  const x=Math.max(-w/2+Math.min(hx,w/2),Math.min(w/2-Math.min(hx,w/2),Math.round((p.x+w/2-hx)/2)*2-w/2+hx)),z=Math.max(-d/2+Math.min(hz,d/2),Math.min(d/2-Math.min(hz,d/2),Math.round((p.z+d/2-hz)/2)*2-d/2+hz));
  for(const [cx,cz,edge] of [[-w/2-hx,z,Math.abs(p.x+w/2)],[w/2+hx,z,Math.abs(p.x-w/2)],[x,-d/2-hz,Math.abs(p.z+d/2)],[x,d/2+hz,Math.abs(p.z-d/2)]]){const distance=Math.hypot(cx-p.x,cz-p.z),inside=hit.entity===e,score=inside?edge:distance;if((!inside&&distance>1.25)||score>=bestScore)continue;const v=V(cx,0,cz).applyAxisAngle(V(0,1,0),e.rotation.y).add(e.position),matrix=new THREE.Matrix4().compose(V(v.x,0,v.z),new THREE.Quaternion().setFromEuler(rotation),V(1,1,1)),box=orientedBox(new THREE.Box3(V(-width/2,-1,-depth/2),V(width/2,1,depth/2)),matrix);
   if(this.entities.some(other=>{if(other===e||other.id!=='foundation')return false;const m=new THREE.Matrix4().compose(V(other.position.x,0,other.position.z),other.mesh.quaternion,V(1,1,1));return boxesOverlap(box,orientedBox(new THREE.Box3(V(-(other.params.width||6)/2,-1,-(other.params.depth||6)/2),V((other.params.width||6)/2,1,(other.params.depth||6)/2)),m),.025);}))continue;
   bestScore=score;best={x:v.x,z:v.z,y:e.position.y,entity:e};}
 }return best;}
 propose(item,camera,rotation,dimensions){const p=placement(this,item,camera,rotation,dimensions);if(!p.position)return p;const {position,params}=p,rot=p.rotation;
  if(Math.hypot(position.x,position.z)>592){p.valid=false;p.reason='Construye dentro del área de exploración.';}
  const geo=createProp(item.id,this.ghostMaterial,params);geo.position.copy(position);geo.rotation.copy(rot);geo.updateMatrixWorld(true);let bounds=geo.geometry.boundingBox.clone().applyMatrix4(geo.matrixWorld);if(item.surface==='floor'&&!['foundation','roof'].includes(item.kind)&&p.hit?.normal?.y>.5&&(Math.abs(Math.sin(rot.x))>.001||Math.abs(Math.sin(rot.z))>.001)){const plane=this.support(position.x,position.z,p.hit.point.y);position.y+=plane-bounds.min.y;geo.position.copy(position);geo.updateMatrixWorld(true);bounds=geo.geometry.boundingBox.clone().applyMatrix4(geo.matrixWorld);}const boxes=entityBoxes(geo.geometry,geo.matrixWorld);
  if(this.entities.some(e=>e.id===item.id&&e.position.distanceTo(position)<.04&&e.mesh.quaternion.angleTo(geo.quaternion)<.015)){p.valid=false;p.reason='Ya hay una pieza en este sitio.';p.overlap=true;}
  for(const e of this.entities){if(!bounds.intersectsBox(e.bounds))continue;const joint=['wall','window','door','corner'].includes(item.kind)&&['wall','window','door','corner'].includes(e.item.kind),railJoint=item.kind==='rail'&&e.item.kind==='rail'&&[ -1,1 ].some(a=>[ -1,1 ].some(b=>V(a*item.size[0]/2,0,0).applyMatrix4(geo.matrixWorld).distanceTo(V(b*e.item.size[0]/2,0,0).applyMatrix4(e.mesh.matrixWorld))<.08)),tolerance=joint?.11:railJoint?.075:.025;
   if(boxes.some(a=>e.colliders.some(b=>{if(item.kind==='ramp'&&e.item.kind==='ramp'&&a.rail&&b.rail&&Math.abs(a.axes[0].dot(b.axes[0]))>.999&&Math.abs(a.axes[2].dot(b.axes[2]))>.999)return boxesOverlap(a,b,.075);return boxesOverlap(a,b,tolerance);}))){p.valid=false;p.reason='Hay otra pieza ocupando ese espacio.';p.overlap=true;break;}}
  const body=orientedBox(new THREE.Box3(V(-.24,-1.6,-.24),V(.24,.1,.24)),new THREE.Matrix4().makeTranslation(...camera.position.toArray()));if(boxes.some(b=>boxesOverlap(b,body,.015))){p.valid=false;p.reason='Aléjate un poco para colocar la pieza.';}
  if(geo.geometry.userData.owned)geo.geometry.dispose();return p;
 }
 spawnDrop(stack,position,velocity,age=0){const mesh=createProp(stack.id,this.material);mesh.scale.setScalar(.23/Math.max(...ITEMS[stack.id].size));mesh.position.copy(position);mesh.updateMatrixWorld(true);this.scene.add(mesh);const d={stack:{...stack},mesh,velocity:velocity.clone(),age,grounded:false};this.drops.push(d);this.dirty=true;return d;}
 throwStack(stack,camera){camera.getWorldDirection(this._v);this._v.y=Math.max(-.15,this._v.y);this._v.normalize();const velocity=this._v.clone().multiplyScalar(8);velocity.y=Math.max(2.8,velocity.y+2.8);const p=camera.position.clone().addScaledVector(this._v,.45);this.spawnDrop(stack,p,velocity);return true;}
 updateDrops(dt){for(const d of this.drops){d.age+=dt;if(d.grounded)continue;const steps=Math.ceil(dt*120),step=dt/steps;for(let i=0;i<steps;i++){const before=this._dropBefore.copy(d.mesh.position);d.velocity.y-=this.gravity*step;d.mesh.position.addScaledVector(d.velocity,step);this.collide(d.mesh.position,before,.12,.22);if(Math.abs(d.mesh.position.x-before.x)<.00001)d.velocity.x*=-.2;if(Math.abs(d.mesh.position.z-before.z)<.00001)d.velocity.z*=-.2;const floor=this.support(d.mesh.position.x,d.mesh.position.z,before.y)+.06;if(d.mesh.position.y<=floor){d.mesh.position.y=floor;d.grounded=true;d.velocity.set(0,0,0);this.dirty=true;break;}}if(!d.grounded)d.mesh.rotation.y+=dt*2;d.mesh.updateMatrixWorld();}}
 pickup(drop,inventory){const left=inventory.add(drop.stack.id,drop.stack.qty);if(left===drop.stack.qty)return false;if(left)drop.stack.qty=left;else{this.scene.remove(drop.mesh);if(drop.mesh.geometry.userData.owned)drop.mesh.geometry.dispose();this.drops.splice(this.drops.indexOf(drop),1);}this.dirty=true;this.save();return true;}
 updateMask(camera){if(this.lunar||this.terrain.grassEnabled===false)return;const x=Math.floor(camera.position.x/16)*16-32,z=Math.floor(camera.position.z/16)*16-32;if(!this.maskDirty&&this.maskOrigin.x===x&&this.maskOrigin.y===z)return;this.maskOrigin.set(x,z);this.maskData.fill(0);
  for(const e of this.entities){if(!['floor','foundation'].includes(e.item.kind))continue;const b=e.bounds,minX=Math.max(0,Math.floor((b.min.x-x)*8)),maxX=Math.min(511,Math.floor((b.max.x-x)*8)),minZ=Math.max(0,Math.floor((b.min.z-z)*8)),maxZ=Math.min(511,Math.floor((b.max.z-z)*8));for(let zz=minZ;zz<=maxZ;zz++)for(let xx=minX;xx<=maxX;xx++){const p=this._maskP.set(x+(xx+.5)/8,e.position.y,z+(zz+.5)/8).applyMatrix4(e.inverse),w=e.params.width||e.item.size[0],d=e.params.depth||e.item.size[2];if(Math.abs(p.x)<=w/2&&Math.abs(p.z)<=d/2)this.maskData[zz*512+xx]=255;}}this.mask.needsUpdate=true;this.maskDirty=false;
 }
 configureGraphics(options){this.lights.configureGraphics(options);}
 update(camera,sky,state,t,dt){this.batches.update(this);updatePropMaterial(this.material,sky,camera,state);updatePropMaterial(this.ghostMaterial,sky,camera,state);this.lights.update(this,camera.position,t);this.updateDrops(dt);this.updateMask(camera);if(this.dirty&&t-(this.lastSave||0)>1){this.lastSave=t;this.save();}}
 distanceTo(e,point){this._v.copy(point);this._v.y=Math.max(e.bounds.min.y,Math.min(e.bounds.max.y,point.y-1.3));e.bounds.clampPoint(this._v,this._p);return this._v.distanceTo(this._p);}
 powered(e){return this.entities.some(p=>['solar','power'].includes(p.item.kind)&&p.position.distanceToSquared(e.position)<18*18);}
}
