import {ITEMS,itemIcon} from './items.js?v=4.0.0';
const GUIDES={
 identifier:['Identificar y registrar','Selecciona este instrumento y lleva el punto central a la Luna, el Sol, un planeta o una estrella visible. Mantén el botón de acción o el clic hasta completar el círculo.','El nombre aparece al apuntar. Tras mantenerlo unos instantes, la observación entra en tu cuaderno.','Para reconocer el cielo y desbloquear filtros. Si no encuentras un planeta, usa primero el visor celeste.'],
 visor:['Encontrar astros','Selecciona las gafas para ponértelas. Aparecen etiquetas sobre los astros que tienes delante y una tonalidad azul verdosa suave. El botón de acción permite apagarlas; cambiar de casilla también las quita.','Verás nombres y distancias aproximadas de los planetas, el Sol y la Luna/Tierra. Las estrellas muestran temperatura estimada; su distancia no está en este catálogo y no se inventa.','Úsalo para localizar un astro antes de identificarlo o apuntar el telescopio. Las etiquetas se ocultan detrás del terreno y de construcciones.'],
 rangefinder:['Medir con un láser','Selecciona el telémetro y apunta. El rayo sale junto a tu mano derecha; la cifra se actualiza mientras miras. No necesitas mantener pulsado.','Verás un punto luminoso sobre superficies cercanas y su distancia. Hacia el cielo el rayo se desvanece gradualmente; sin impacto no muestra una medida falsa.','Para medir separaciones entre vehículos, paredes, instrumentos y terreno. Alcance de medida: 600 m.'],
 spectrometer:['Leer el color de una estrella','Apunta a una estrella del catálogo y pulsa acción. Se abre una tarjeta con su color, temperatura aproximada, clase térmica y curva. Pulsa Guardar observación para registrarla.','Una curva térmica calculada a partir de B−V. No es un espectro medido; para Luna y planetas utiliza el identificador.','Para comparar estrellas frías y calientes y conservar los resultados en el cuaderno.'],
 sampler:['Recoger una muestra','Apunta a suelo natural a menos de tres metros y pulsa acción. Cada pulsación recoge una muestra si hay espacio en la mochila.','En Tierra recibes suelo; en Luna, regolito. No se puede muestrear una pared ni un piso construido.','Lleva la muestra a una mesa de análisis con un módulo de energía o panel solar cercano.'],
 camera:['Fotografiar una observación','Selecciona la cámara, encuadra y pulsa acción. La foto pequeña y los datos de la escena se guardan en el cuaderno.','Si apuntas a un astro identificado, el registro lleva su nombre. También puedes fotografiar el paisaje y tu base.','Para documentar una exploración sin llenar la mochila de objetos.'],
 notebook:['Consultar tu cuaderno','Pulsa acción con el cuaderno seleccionado, la tecla J o interactúa con un escritorio.','Aquí están tus registros y descubrimientos. Puedes cambiar la fecha del catálogo planetario y exportar/importar toda la expedición.','Exporta para conservar tus bases y observaciones al cambiar de navegador o dispositivo.'],
 telescope:['Mirar desde un observatorio','Colócalo orientado al cielo. Acércate y usa Mirar/E. Mueve la mirada para girar el tubo y elige un aumento. Usa Salir/E para levantarte.','El último aumento muestra los discos de los siete planetas. El tubo conserva la dirección al salir. Una pared o un techo pueden tapar el ocular.','El botón de bandas abre Visible y filtros didácticos en falso color; los avanzados se desbloquean experimentando y requieren energía cercana.'],
 lab:['Analizar muestras','Coloca la mesa junto a un panel solar o módulo de energía, a menos de 18 m. Lleva suelo/regolito en la mochila, acércate y pulsa Analizar/E.','Confirma para consumir una unidad y guardar una ficha educativa. Analizar regolito desbloquea el filtro de rayos X.','Los datos representan composiciones típicas; no son mediciones químicas del paisaje del juego.'],
 radio:['Sintonizar señales','Coloca energía a menos de 18 m, acércate a la antena y pulsa Escuchar/E. Mueve la frecuencia y detente cerca de 32 MHz, 400 MHz o 160 GHz.','Una señal sintonizada se registra tras un instante. Si tienes el sonido activo, cambia lo que escuchas.','Son ejemplos sonoros sintetizados; registrar uno desbloquea radio/microondas.'],
 seismometer:['Ver vibraciones','Coloca el instrumento, acércate y pulsa Registrar/E. Puedes guardar el registro desde su tarjeta.','La gráfica va dibujando pequeñas vibraciones y eventos periódicos.','Es una simulación didáctica de actividad del suelo, distinta para cada entorno en su descripción.'],
 weather:['Consultar el ambiente','Colócala, acércate y pulsa Consultar/E.','En Tierra muestra temperatura, viento e iluminación simulados según la hora. En la Luna informa de la ausencia de clima terrestre.','Para acompañar las observaciones de tu puesto; no consulta el tiempo real.'],
 beacon:['Marcar un lugar','Coloca una baliza y usa Nombrar/E cerca de ella. Escribe un nombre corto y guárdalo.','Cuando mires en esa dirección aparecerán el nombre y la distancia discretamente bajo la brújula.','Para localizar tu Base, Observatorio o un cráter al que quieras regresar.'],
 solar:['Dar energía a los aparatos','Coloca un panel cerca de tu puesto. No necesitas cables ni combustible.','Habilita mesas de análisis, antenas y bandas avanzadas del telescopio dentro de 18 m.','Puedes usar un panel solar o un módulo de energía. No hay que mantenerlos ni recargarlos.'],
 power:['Dar energía a los aparatos','Coloca el módulo a menos de 18 m de los instrumentos.','Funciona como el panel solar: habilita instrumentos avanzados sin cables.','Útil dentro de puestos pequeños y compartido entre Tierra y Luna.'],
 lamp:['Controlar una lámpara','Apunta directamente a una lámpara y usa el botón de encendido de la derecha. Para cambiar la temperatura, acércate y pulsa Iluminar/E.','Puedes encenderla/apagarla sin abrir una ventana; su menú conserva las opciones cálida, neutra y fría.','Las lámparas de pie, pared y techo comparten este manejo.'],
 foundation:['Ampliar una plataforma','Selecciona un cimiento y elige ancho/fondo. Apunta al borde de otro: el fantasma se une a su altura. Pulsa + para colocarlo.','La cara superior queda plana y el cuerpo rellena hacia abajo. Si el terreno sobresale del nivel existente, el fantasma avisa y no lo coloca enterrado.','En Luna es el apoyo previo de pisos y paredes. Puedes unir varios; en Tierra es opcional.'],
 'ramp-adaptive':['Acceder a un cimiento','Apunta a un borde del cimiento o piso. La rampa busca el terreno en esa dirección, ajusta su longitud y rellena por debajo. Coloca con + o clic derecho.','La parte superior se une al nivel del cimiento. La pendiente máxima es del 40 % y la longitud se adapta hasta 48 m. Un aviso indica si el borde no admite la rampa.','Para plataformas en laderas y cráteres. También hay dos rampas suaves de altura fija y un escalón ancho de 0,4 m.'],
 floor:['Construir con piezas','Selecciona una pieza de acceso rápido. Mira dónde colocarla. Arrastra los anillos para girar libremente. La flecha despliega tres barras X/Y/Z de 0 a 360°. El botón de giro o R ajusta 90° en el eje elegido. Pulsa +, Enter o clic derecho para confirmar.','Arrastrar el paisaje mueve la mirada y conserva el fantasma. Dar un toque breve al paisaje cancela construcción y elimina el fantasma. Toca otra vez la casilla para continuar.','Pisos, paredes y cubiertas comparten una cuadrícula invisible. Para el techo mira el borde alto de una pared desde dentro o el hueco sobre la habitación. El lápiz entra en edición sin fantasma: mira una pieza y pulsa papelera/Supr. Ctrl+Z deshace y Ctrl+Y rehace.'],
 chair:['Sentarte y mirar','Acércate a medio metro de una silla o banco. Usa Sentarse/E y conserva la mirada libre. Usa Salir/E para levantarte.','El icono está anclado al asiento. No necesitas abrir la mochila para usarlo.','Coloca asientos en tu puesto de observación, en Tierra o Luna.'],
 storage:['Guardar un stack','Acércate a una caja y pulsa Abrir/E. Depositar guarda el acceso rápido seleccionado; toca un stack de la caja para recuperarlo.','La caja tiene diez espacios adicionales, con hasta 30 unidades por stack.','Vacía la caja antes de recuperarla como objeto.'],
 desk:['Revisar observaciones','Acércate al escritorio y pulsa Cuaderno/E.','Abre el mismo cuaderno que J o la herramienta portátil.','Úsalo como estación de trabajo de tu base.']
};
export class FieldGuide{
 constructor(expedition){this.x=expedition;}
 show(id){const source=ITEMS[id];id=GUIDES[id]?id:source?.category==='Construcción'?'floor':source?.category==='Iluminación'?'lamp':source?.kind==='stool'?'chair':'identifier';const x=this.x,keys=Object.keys(GUIDES);const content=x.dialog('Guía de campo',`<p class="guide-intro">Elige un instrumento para saber cómo usarlo. Puedes volver con ? o H. E abre la mochila; cerca de un objeto sirve para interactuar. B abre siempre la mochila. Shift + clic mueve stacks; 1–9/0 sobre una casilla intercambia con la mano; Q lanza una unidad y Ctrl+Q el stack. La rueda cambia de casilla. F1 oculta la interfaz.</p><div class="field-guide"><nav class="guide-items" aria-label="Instrumentos y controles">${keys.map(key=>`<button data-guide="${key}" aria-pressed="${key===id}">${itemIcon(key)}<span>${ITEMS[key].name}</span></button>`).join('')}</nav><article class="guide-detail" aria-live="polite"></article></div>`);
  const select=key=>{const [title,use,expect,when]=GUIDES[key],detail=content.querySelector('.guide-detail');detail.innerHTML=`<div class="guide-icon">${itemIcon(key)}</div><p class="eyebrow">${ITEMS[key].name}</p><h3>${title}</h3><h4>Cómo se usa</h4><p>${use}</p><h4>Qué verás</h4><p>${expect}</p><h4>Para qué sirve</h4><p>${when}</p>`;detail.scrollTop=0;content.querySelectorAll('[data-guide]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.guide===key));};content.querySelectorAll('[data-guide]').forEach(b=>b.onclick=()=>select(b.dataset.guide));select(id);
 }
 firstVisit(){const state=this.x.state;if(!state.active||state.panel||state.inventory||state.expeditionPanel)return;const key='sky-guide-'+state.destination+'-31';try{if(localStorage.getItem(key))return;localStorage.setItem(key,'seen');}catch{}this.show();}
}
