import * as THREE from './three.module.js?v=4.0.0';
import {ITEMS,PALETTE as P} from './items.js?v=4.1.1';
import {flashlightGLSL,vehicleLightGLSL,vehicleLightUniforms,updateVehicleLightUniforms} from './flashlight.js?v=4.1.1';
import {worldLightGLSL,worldUniforms} from './world-lighting.js?v=4.1.1';
const V=(a)=>new THREE.Vector3(...a),cache=new Map();
// Each authored prop is one merged, coloured mesh. Shared immutable geometry
// is reused across instances, ghost previews and pickups; no external models.
class Parts{
 constructor(){this.p=[];this.n=[];this.c=[];this.e=[];this.boxes=[];this.colliders=[];this.shadowParts=[];}
 add(g,col,pos=[0,0,0],rot=[0,0,0],glow=0,castsShadow=true){const original=g;g=g.index?g.toNonIndexed():g;const matrix=new THREE.Matrix4().compose(V(pos),new THREE.Quaternion().setFromEuler(new THREE.Euler(...rot)),V([1,1,1]));g.computeBoundingBox();if(glow<=0&&castsShadow)this.shadowParts.push({box:g.boundingBox.clone(),matrix:matrix.clone()});g.applyMatrix4(matrix);const p=g.attributes.position,n=g.attributes.normal,c=new THREE.Color(col);for(let i=0;i<p.count;i++){this.p.push(p.getX(i),p.getY(i),p.getZ(i));this.n.push(n.getX(i),n.getY(i),n.getZ(i));this.c.push(c.r,c.g,c.b);this.e.push(glow);}g.dispose();if(g!==original)original.dispose();return this;}
 box(size,pos,col=P.shell,rot=[0,0,0],glow=0,collide=true){if(collide)this.collider(size,pos,rot);return this.add(new THREE.BoxGeometry(...size),col,pos,rot,glow);}
 collider(size,pos,rot=[0,0,0],rail=false){const box=new THREE.Box3(V(size).multiplyScalar(-.5),V(size).multiplyScalar(.5)),matrix=new THREE.Matrix4().compose(V(pos),new THREE.Quaternion().setFromEuler(new THREE.Euler(...rot)),V([1,1,1]));this.colliders.push({box,matrix,rail});this.boxes.push(box.clone().applyMatrix4(matrix));return this;}
 cylinder(r,h,pos,col=P.frame,rot=[0,0,0],r2=r){return this.add(new THREE.CylinderGeometry(r,r2,h,16),col,pos,rot);}
 tube(a,b,r=.025,col=P.frame){const av=V(a),bv=V(b),g=new THREE.CylinderGeometry(r,r,av.distanceTo(bv),8),q=new THREE.Quaternion().setFromUnitVectors(V([0,1,0]),bv.clone().sub(av).normalize()),rot=new THREE.Euler().setFromQuaternion(q);return this.add(g,col,av.add(bv).multiplyScalar(.5).toArray(),[rot.x,rot.y,rot.z]);}
 finish(){const g=new THREE.BufferGeometry();for(const [name,array,size] of [['position',this.p,3],['normal',this.n,3],['paint',this.c,3],['emission',this.e,1]])g.setAttribute(name,new THREE.Float32BufferAttribute(array,size));g.computeBoundingBox();g.computeBoundingSphere();g.userData.boxes=this.boxes;g.userData.colliders=this.colliders;g.userData.shadowParts=this.shadowParts;return g;}
}
export function propMaterial(lunar=false,ghost=false,instanced=false){const u={...vehicleLightUniforms(),...worldUniforms(),sun:{value:V([0,1,0])},earth:{value:V([0,1,0])},day:{value:1},earthPower:{value:0},lunar:{value:+lunar},eye:{value:V([0,0,0])},forward:{value:V([0,0,-1])},torch:{value:0},ghost:{value:+ghost},valid:{value:1},lampColor:{value:new THREE.Color(0xffd6ab)},lampOn:{value:1}};
 const material=new THREE.ShaderMaterial({uniforms:u,transparent:ghost,depthWrite:!ghost,polygonOffset:ghost,polygonOffsetFactor:-1,polygonOffsetUnits:-1,toneMapped:false,vertexShader:`attribute vec3 paint;attribute float emission;${instanced?'attribute vec4 batch0,batch1,batch2,batch3;':''}varying vec3 vWorld,vNormal,vPaint;varying float vEmission;void main(){${instanced?'vWorld=batch0.xyz*position.x+batch1.xyz*position.y+batch2.xyz*position.z+batch3.xyz;vNormal=normalize(batch0.xyz*normal.x+batch1.xyz*normal.y+batch2.xyz*normal.z);':'vWorld=(modelMatrix*vec4(position,1.)).xyz;vNormal=normalize(mat3(modelMatrix)*normal);'}vPaint=paint;vEmission=emission;gl_Position=projectionMatrix*viewMatrix*vec4(vWorld,1.);}`,fragmentShader:`varying vec3 vWorld,vNormal,vPaint;varying float vEmission;uniform vec3 sun,earth,eye,forward,lampColor;uniform float day,earthPower,lunar,torch,ghost,valid,lampOn;${flashlightGLSL}${vehicleLightGLSL}${worldLightGLSL}
 void main(){if(ghost>.5){vec3 tint=mix(vec3(.95,.38,.28),vec3(.51,.89,.82),valid);float edge=pow(1.-abs(dot(normalize(vNormal),normalize(eye-vWorld))),2.);gl_FragColor=vec4(tint,.22+edge*.30);return;}
 vec3 n=normalize(vNormal),p=vWorld+n*.025;float solar=0.;if(sun.y>0.)solar=max(0.,dot(n,sun));vec3 light=mix(vec3(.013,.018,.025)+vec3(.17)*day,vec3(.00004),lunar);
 if(solar>.001)light+=vec3(1.,.96,.88)*solar*mix(day*.8,1.35,lunar)*baseDirectionalVisibility(p,sun,0.)*vehicleOcclusion(p,sun);
 float earthLit=max(0.,dot(n,earth));if(earthPower>.0001&&earthLit>.001)light+=vec3(.46,.63,1.)*earthLit*earthPower*baseDirectionalVisibility(p,earth,1.);
 if(torch>.001){float beam=flashlightBeam(vWorld-eye,forward)*torch;if(beam>.001)light+=vec3(.92,.96,1.)*beam*(.1+.9*max(dot(n,normalize(eye-vWorld)),0.));}
 if(lampMode>.001){float l=headlightBeam(vWorld-lampLeft),r=headlightBeam(vWorld-lampRight);if(l>.001)light+=vec3(.92,.96,1.)*l*max(.15,dot(n,normalize(lampLeft-vWorld)))*basePointVisibility(vWorld,n,lampLeft,29);if(r>.001)light+=vec3(.92,.96,1.)*r*max(.15,dot(n,normalize(lampRight-vWorld)))*basePointVisibility(vWorld,n,lampRight,30);}
 float rear=rearBeam(vWorld);if(rear>.001)light+=vec3(1.,.009,.002)*rear*basePointVisibility(vWorld,n,rearLamp,31);
 light+=baseLighting(vWorld,n);vec3 color=vPaint*light;if(vEmission>0.)color+=lampColor*vEmission*lampOn;if(vEmission<0.)color+=vPaint*(-vEmission)*.32;
 gl_FragColor=vec4(pow(max(color,vec3(0.)),vec3(1./2.2)),1.);}`});return material;}
export function updatePropMaterial(mat,sky,camera,state){const u=mat.uniforms;u.sun.value.copy(sky.sun);u.earth.value.copy(sky.moon);u.day.value=sky.day??sky.u.day.value;u.earthPower.value=state.destination==='moon'?sky.earthshine:sky.u.moonlight.value*.18;u.eye.value.copy(camera.position);camera.getWorldDirection(u.forward.value);u.torch.value=state.flashlight?1:0;updateVehicleLightUniforms(u,state.vehicleLighting);}
function feet(p,w,d,y){for(const x of [-w/2+.08,w/2-.08])for(const z of [-d/2+.08,d/2-.08])p.box([.06,y,.06],[x,y/2,z],P.frame);}
function panel(p,w,h,z=0){p.box([w-.18,h,.12],[0,h/2,z],P.shell).box([w,.14,.17],[0,.18,z],P.blue).box([w,.055,.17],[0,h-.09,z],P.gold);for(const x of [-w/2+.045,w/2-.045])p.box([.09,h,.19],[x,h/2,z],P.frame);}
export function propGeometry(id,params={}){
 const item=ITEMS[id];if(!item)throw Error('Objeto desconocido');const [w,h,d]=item.size,key=id+((['foundation','telescope'].includes(item.kind)||item.adaptive)?JSON.stringify(params):'');if(cache.has(key))return cache.get(key);const p=new Parts(),k=item.kind;
 if(k==='foundation'){const width=params.width||6,depth=params.depth||6,fill=Math.max(.30,params.fill||1);p.box([width,fill-.16,depth],[0,-.16-(fill-.16)/2,0],P.frame).box([width,.16,depth],[0,-.08,0],P.shell);}
 else if(k==='floor'||k==='roof'){p.box([w,h,d],[0,h/2,0],k==='floor'?P.frame:P.shell);for(const x of [-w/2+.06,w/2-.06])p.box([.10,.004,d],[x,h+.002,0],P.teal,[0,0,0],0,false);for(const z of [-d/2+.06,d/2-.06])p.box([w,.004,.10],[0,h+.002,z],P.teal,[0,0,0],0,false);for(let x=-w/2+1;x<w/2;x++)p.box([.012,.004,d-.18],[x,h+.002,0],P.dark,[0,0,0],0,false);}
 else if(k==='wall')panel(p,w,h);
 else if(k==='window'||k==='door'){const opening=k==='door'?(id==='door-wide'?2.4:id==='door-gate'?4:1.35):2.7,side=(w-opening)/2;for(const x of [-1,1])if(side>0)p.box([side,h,.16],[x*(opening/2+side/2),h/2,0],P.shell);const low=k==='door'?0:.85,top=k==='door'?2.25:2.2;if(low)p.box([opening,low,.16],[0,low/2,0],P.blue);p.box([opening,h-top,.16],[0,(h+top)/2,0],P.shell);for(const x of [-opening/2-(id==='door-gate'?.035:0),opening/2+(id==='door-gate'?.035:0)])p.box([.07,top-low,.21],[x,(top+low)/2,0],P.teal);p.box([opening+.12,.07,.21],[0,top,0],P.gold);if(low)p.box([opening,.08,.32],[0,low,0],P.frame);}
 else if(k==='corner'){panel(p,1,h);p.box([.16,h,1],[.42,h/2,-.42],P.shell).box([.18,.14,1],[.42,.18,-.42],P.blue);}
 else if(k==='column')p.box([w,h,d],[0,h/2,0],P.frame).box([.44,.1,.44],[0,.05,0],P.teal).box([.44,.1,.44],[0,h-.05,0],P.gold);
 else if(k==='ramp'){
  const w=Math.max(1,Math.min(24,Number(params.width)||item.size[0])),run=Math.max(.5,Math.min(48,Number(params.run)||d)),rise=Math.max(.05,Math.min(30,Number(params.rise)||h)),segments=24,positions=[];
  const triangle=(a,b,c)=>positions.push(...a,...b,...c),quad=(a,b,c,d)=>{triangle(a,b,c);triangle(a,c,d);};
  for(let i=0;i<segments;i++){const t=i/segments,u=(i+1)/segments,z=-run/2+run*t,zz=-run/2+run*u,y=rise*(1-t),yy=rise*(1-u),lo=Math.min(y-.045,params.profile?.[i]??-.06),ll=Math.min(yy-.045,params.profile?.[i+1]??-.06);
   quad([-w/2,y,z],[-w/2,yy,zz],[w/2,yy,zz],[w/2,y,z]);quad([-w/2,lo,z],[w/2,lo,z],[w/2,ll,zz],[-w/2,ll,zz]);quad([-w/2,lo,z],[-w/2,ll,zz],[-w/2,yy,zz],[-w/2,y,z]);quad([w/2,lo,z],[w/2,y,z],[w/2,yy,zz],[w/2,ll,zz]);
   if(i===0)quad([-w/2,lo,z],[-w/2,y,z],[w/2,y,z],[w/2,lo,z]);if(i===segments-1)quad([-w/2,ll,zz],[w/2,ll,zz],[w/2,yy,zz],[-w/2,yy,zz]);
   const bottom=Math.min(lo,ll),height=Math.max(.06,(y+yy)/2-bottom);p.collider([w,height,run/segments],[0,bottom+height/2,(z+zz)/2]);p.shadowParts.push(p.colliders[p.colliders.length-1]);
  }
  const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));geometry.computeVertexNormals();const shadowCount=p.shadowParts.length;p.add(geometry,P.blue);p.shadowParts.length=shadowCount;
  for(const x of [-w/2+.04,w/2-.04]){p.tube([x,rise+.01,-run/2],[x,.01,run/2],.016,P.gold);if(params.rails??(item.adaptive?!id.endsWith('open')&&id!=='ramp-adaptive-wide':rise>.65)){p.tube([x,rise+.9,-run/2],[x,.9,run/2],.026,P.teal);for(let segment=0;segment<8;segment++){const t=(segment+.5)/8;p.collider([.065,.9+rise/8,run/8],[x,rise*(1-t)+.45,-run/2+run*t],[0,0,0],true);}for(let i=0;i<=Math.ceil(run/2);i++){const t=i/Math.ceil(run/2);p.tube([x,rise*(1-t),-run/2+run*t],[x,rise*(1-t)+.9,-run/2+run*t],.023);}}}
 }
 else if(k==='stairs'){const n=Math.max(2,Math.round(h/.2));for(let i=0;i<n;i++){const sh=(i+1)*h/n,zz=d/2-(i+.5)*d/n;p.box([w,sh,d/n],[0,sh/2,zz],i%2?P.frame:P.blue);p.box([w,.014,.04],[0,sh+.007,zz+d/n/2-.03],P.gold,[0,0,0],0,false);}if(h>.65)for(const x of [-w/2,w/2]){p.tube([x,1,d/2],[x,h+1,-d/2],.025,P.teal);for(const z of [-d/2,d/2]){const y=z<0?h:0;p.tube([x,y,z],[x,y+1,z],.025);}}}
 else if(k==='rail'){p.collider([w,h,.065],[0,h/2,0],[0,0,0],true);p.tube([-w/2,h,0],[w/2,h,0],.03,P.teal);p.tube([-w/2,.55,0],[w/2,.55,0],.02);for(const x of [-w/2,0,w/2])p.box([.055,h,.055],[x,h/2,0],P.frame);}
 else if(['table','lab','desk'].includes(k)){p.box([w,.09,d],[0,.80,0],P.shell);feet(p,w,d,.76);p.box([w-.12,.018,.06],[0,.855,-d/2+.06],P.teal,[0,0,0],0,false);p.box([.20,.018,.025],[-w/2+.18,.855,d/2-.08],P.gold,[0,0,0],0,false);p.box([w,.05,.06],[0,.74,d/2],P.teal);if(k!=='table'){p.box([.54,.32,.055],[.24,1,-.22],P.dark,[-.13,0,0]);p.box([.45,.22,.012],[.24,1,-.176],P.teal,[-.13,0,0],-1);p.box([.50,.035,.16],[.24,.87,.08],P.frame);for(let i=0;i<6;i++)p.box([.045,.005,.015],[-.03+i*.075,.89,.08],P.white);}if(k==='lab'){p.cylinder(.1,.28,[-.55,.99,0],P.gold);p.box([.26,.05,.3],[-.55,.86,0],P.blue);p.tube([-.66,.9,-.16],[-.66,1.14,-.16],.015);}}
 else if(k==='chair'||k==='stool'){feet(p,w,d,.43);p.box([w,.1,d],[0,.47,0],P.teal);if(k==='chair'){p.box([w,.42,.085],[0,.71,d/2-.03],P.shell,[-.09,0,0]);for(const x of [-w/2,w/2])p.tube([x,.4,d/2],[x,.89,d/2+.03],.023);}}
 else if(k==='shelf')p.box([w,.06,d],[0,h,0],P.shell).box([w,.24,.035],[0,h/2,-d/2],P.blue);
 else if(k==='cabinet'||k==='storage'||k==='power'){p.box([w,h,d],[0,h/2,0],k==='power'?P.blue:P.frame).box([w-.06,h-.06,.03],[0,h/2,d/2+.01],P.shell);for(const y of [.15,h-.15])p.box([w,.055,d+.035],[0,y,0],P.teal);p.box([.22,.035,.025],[0,h*.6,d/2+.04],P.gold);if(k==='power')for(let i=0;i<3;i++)p.box([.08,.05,.03],[-.15+i*.15,h*.8,d/2+.04],P.teal,[0,0,0],-1);}
 else if(k==='rack'){feet(p,w,d,h);for(const y of [.1,.6,1.2,1.8])p.box([w,.055,d],[0,y,0],P.shell);p.tube([-w/2,0,-d/2],[w/2,h,-d/2],.015,P.teal);}
 else if(k==='lamp'){p.cylinder(.17,.05,[0,.025,0]);p.cylinder(.025,1.65,[0,.85,0]);p.cylinder(.15,.23,[0,1.68,0],P.shell);p.box([.27,.19,.19],[0,1.69,0],P.white,[0,0,0],1);p.box([.35,.035,.25],[0,1.8,0],P.blue);}
 else if(k==='wall-lamp'){p.box([w,h,.06],[0,h/2,0],P.blue);p.box([w-.06,h-.12,.08],[0,h/2,.065],P.white,[0,0,0],1);}
 else if(k==='ceiling-lamp')p.box([w,h,d],[0,-h/2,0],P.frame).box([w-.08,.02,d-.08],[0,-h-.005,0],P.white,[0,0,0],1);
 else if(k==='telescope'){
  const pitch=Number.isFinite(params.pitch)?params.pitch:.38,yaw=Number(params.azimuth)||0,axis=new THREE.Vector3(Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),-Math.cos(yaw)*Math.cos(pitch)),center=new THREE.Vector3(0,1.42,-.2),q=new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0,1,0),axis),r=new THREE.Euler().setFromQuaternion(q),orientation=[r.x,r.y,r.z],front=center.clone().addScaledVector(axis,.5),back=center.clone().addScaledVector(axis,-.6);
  for(let i=0;i<3;i++){const a=i*Math.PI*2/3;p.tube([0,1,0],[Math.cos(a)*.55,.02,Math.sin(a)*.55],.027);p.cylinder(.04,.04,[Math.cos(a)*.55,.02,Math.sin(a)*.55],P.teal);}
  p.cylinder(.1,.25,[0,1,0],P.frame);p.tube([0,1.08,0],center.toArray(),.05,P.teal);p.cylinder(.19,1,center.toArray(),P.shell,orientation);p.cylinder(.205,.055,front.toArray(),P.blue,orientation);p.cylinder(.16,.02,front.clone().addScaledVector(axis,.035).toArray(),P.dark,orientation);p.cylinder(.055,.16,back.toArray(),P.dark,orientation);p.box([.32,.09,.2],[.25,1.03,.07],P.teal);p.collider([.24,1,.24],[0,.5,0]);
 }
 else if(k==='radio'){
  p.box([.62,.30,.52],[0,.15,0],P.blue);p.box([.50,.16,.025],[0,.17,.276],P.frame);for(const x of [-.15,.15])p.cylinder(.038,.02,[x,.17,.295],P.gold,[Math.PI/2,0,0]);p.cylinder(.043,1.23,[0,.90,0]);p.tube([0,1.4,0],[0,1.64,-.04],.065,P.teal);
  const center=new THREE.Vector3(0,1.64,-.04),q=new THREE.Quaternion().setFromEuler(new THREE.Euler(.30,0,0)),at=(x,y,z)=>new THREE.Vector3(x,y,z).applyQuaternion(q).add(center).toArray(),positions=[];
  const tri=(a,b,c)=>positions.push(...at(...a),...at(...b),...at(...c));const radius=.62,curve=r=>-.20*(r/radius)**2;
  for(let i=0;i<32;i++)for(let j=0;j<7;j++){const a=i/32*Math.PI*2,b=(i+1)/32*Math.PI*2,r=j/7*radius,s=(j+1)/7*radius;for(const back of [false,true]){const z=back?.024:0,A=[Math.cos(a)*r,Math.sin(a)*r,curve(r)+z],B=[Math.cos(b)*r,Math.sin(b)*r,curve(r)+z],C=[Math.cos(b)*s,Math.sin(b)*s,curve(s)+z],D=[Math.cos(a)*s,Math.sin(a)*s,curve(s)+z];if(back){tri(A,C,B);tri(A,D,C);}else{tri(A,B,C);tri(A,C,D);}}}
  const dish=new THREE.BufferGeometry();dish.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));dish.computeVertexNormals();p.add(dish,P.shell,[0,0,0],[0,0,0],0,false);p.add(new THREE.TorusGeometry(radius,.017,6,48),P.teal,at(0,0,-.19),[.30,0,0],0,false);
  // The curved circular reflector, not its rectangular bounding volume, casts
  // the shadow. Keep the unchanged authored mesh and collision geometry.
  p.shadowParts.push({box:new THREE.Box3(V([-radius,-radius,-.20]),V([radius,radius,.024])),matrix:new THREE.Matrix4().compose(center,q,V([1,1,1])),shape:{radius,curve:.20/(radius*radius),depth:.024}});
  for(let i=0;i<4;i++){const a=i*Math.PI/2;p.tube(at(Math.cos(a)*.56,Math.sin(a)*.56,curve(.56)),at(0,0,-.48),.012,P.gold);for(let j=0;j<6;j++){const r=j*.59/6,t=(j+1)*.59/6;p.tube(at(Math.cos(a)*r,Math.sin(a)*r,curve(r)+.04),at(Math.cos(a)*t,Math.sin(a)*t,curve(t)+.04),.012,P.gold);}}p.cylinder(.042,.10,at(0,0,-.49),P.teal,[Math.PI/2+.30,0,0]);
 }
 else if(k==='solar'){for(const x of [-.7,.7])p.box([.07,.75,.07],[x,.37,0],P.frame);p.box([w,.06,d],[0,.86,0],P.dark,[-.3,0,0]);for(let x=-2;x<=2;x++)for(let z=-1;z<=1;z++)p.box([.42,.012,.43],[x*.46,.91+z*.143,z*.46],x%2?0x365d84:0x3e6891,[-.3,0,0]);for(const x of [-w/2,w/2])p.box([.055,.055,d],[x,.90,0],P.shell,[-.3,0,0]);}
 else if(k==='beacon'){p.cylinder(.17,.08,[0,.04,0]);p.cylinder(.028,1.2,[0,.68,0]);p.box([.25,.14,.20],[0,1.28,0],P.teal,[0,0,0],-1);p.box([.25,.20,.025],[0,.96,.03],P.shell);}
 else if(k==='weather'){p.cylinder(.035,2.1,[0,1.05,0]);for(let i=0;i<3;i++){const a=i*Math.PI*2/3;p.tube([0,.65,0],[Math.cos(a)*.45,0,Math.sin(a)*.45],.025);}p.box([.45,.45,.30],[0,1.45,0],P.shell);for(let i=0;i<4;i++)p.box([.48,.025,.33],[0,1.3+i*.1,0],P.teal);p.tube([-.45,2.1,0],[.45,2.1,0],.018);p.box([.15,.12,.02],[.38,2.16,0],P.gold);}
 else if(k==='seismometer'){p.cylinder(.3,.22,[0,.11,0],P.shell);p.cylinder(.23,.04,[0,.23,0],P.teal);p.box([.22,.08,.1],[0,.31,0],P.gold);for(const x of [-.22,.22])p.box([.06,.05,.12],[x,.025,.20],P.frame);}
 else if(k==='sample'){p.cylinder(.075,.2,[0,.1,0],id==='soil'?0x8e7860:0x8d9498);p.cylinder(.081,.03,[0,.20,0],P.gold);}
 else {p.box([.19,.3,.065],[0,.15,0],P.blue).box([.13,.16,.02],[0,.20,.041],P.teal,[0,0,0],-1).box([.035,.025,.02],[0,.06,.04],P.gold);}
 const g=p.finish();g.userData.owned=k==='foundation'||k==='telescope'||item.adaptive;if(!g.userData.owned)cache.set(key,g);return g;
}
export function createProp(id,material,params={}){const mesh=new THREE.Mesh(propGeometry(id,params),material);mesh.name=ITEMS[id].name;return mesh;}
