import {ITEMS,itemIcon} from './items.js?v=4.1.2';
import {LAMP_TEMPERATURES} from './world-lighting.js?v=4.1.2';
const KEY='sky-expedition-journal-v1';
export const escapeHTML=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const FILTERS=[['visible','Visible','Disponible al comenzar.'],['infrared','Infrarrojo','Observa la Luna con el identificador o telescopio de piso.'],['ultraviolet','Ultravioleta','Identifica tres estrellas distintas.'],['radio','Radio / microondas','Encuentra una señal con la antena.'],['xray','Rayos X','Analiza una muestra lunar.'],['gamma','Gamma','Completa las cuatro observaciones anteriores.']];
export class Science{
 constructor(expedition){this.x=expedition;this.entries=[];this.filter='visible';this.tick=null;this.stopSound=null;try{const saved=JSON.parse(localStorage.getItem(KEY));if(Array.isArray(saved))this.entries=saved.filter(e=>e&&typeof e==='object'&&typeof e.title==='string').slice(-160);}catch{}this.unlocked=this.unlocks();}
 unlocks(){const moon=this.entries.some(e=>e.targetId==='luna'),stars=new Set(this.entries.filter(e=>e.kind==='star').map(e=>e.targetId)).size>=3,radio=this.entries.some(e=>e.kind==='radio'),sample=this.entries.some(e=>e.kind==='analysis'&&e.targetId==='regolith');return ['visible',...(moon?['infrared']:[]),...(stars?['ultraviolet']:[]),...(radio?['radio']:[]),...(sample?['xray']:[]),...(moon&&stars&&radio&&sample?['gamma']:[])];}
 save(){try{localStorage.setItem(KEY,JSON.stringify(this.entries));}catch{this.x.toast('No hay espacio para guardar otra foto. Exporta tu cuaderno.');}}
 record(target,kind=target.kind,note='',photo=null){const state=this.x.state,entry={id:Date.now().toString(36),targetId:target.id||target.name,title:target.name,kind,destination:state.destination,date:this.x.env.celestial.date,hour:state.hour,position:this.x.camera.position.toArray().map(v=>Math.round(v*10)/10),note,photo};this.entries.push(entry);if(this.entries.length>160)this.entries.shift();this.save();const unlocked=this.unlocks(),fresh=unlocked.filter(s=>!this.unlocked.includes(s));this.unlocked=unlocked;if(fresh.length)this.x.toast('Nuevo filtro: '+FILTERS.find(f=>f[0]===fresh[0])[1]);else this.x.toast('Registrado: '+entry.title);return entry;}
 close(){this.tick=null;this.stopSound?.();this.stopSound=null;}
 observe(target){if(!target)return this.x.toast('Apunta a un astro visible.');const note=target.kind==='planet'?'Distancia geocéntrica aproximada: '+target.distance.toFixed(2)+' ua. Efemérides JPL; orientación de juego.':target.kind==='star'?'Magnitud '+target.magnitude.toFixed(2)+' · clase aproximada '+target.type+' · '+target.temperature+' K estimados.':'Observación visual.';this.record(target,target.kind,note);}
 spectrum(target){if(target?.kind!=='star')return this.x.toast('Apunta a una estrella del catálogo.');const node=this.x.dialog('Analizador espectral',`<p class="eyebrow">${escapeHTML(target.name)}</p><div class="science-stat">${target.temperature.toLocaleString('es')} <small>K estimados</small></div><p>Color B−V: ${target.bv.toFixed(2)} · Clase aproximada ${target.type} · Magnitud ${target.magnitude.toFixed(2)}</p><svg class="spectrum-plot" viewBox="0 0 500 140" role="img" aria-label="Continuo térmico aproximado entre 380 y 780 nanómetros"><defs><linearGradient id="spectrum-rainbow"><stop stop-color="#805cef"/><stop offset=".22" stop-color="#518fde"/><stop offset=".45" stop-color="#80cba7"/><stop offset=".7" stop-color="#edce85"/><stop offset="1" stop-color="#d38175"/></linearGradient></defs><rect x="0" y="0" width="500" height="140" fill="url(#spectrum-rainbow)" opacity=".22"/><path id="spectrum-line" fill="none" stroke="#f5ecd6" stroke-width="2"/></svg><div class="science-scale"><span>380 nm</span><span>780 nm</span></div><p class="science-note">Continuo de cuerpo negro calculado a partir del color del catálogo. Temperatura aproximada; no es un espectro medido ni una clasificación espectroscópica.</p><button class="science-primary" id="record-spectrum">Guardar observación</button>`);
  const values=Array.from({length:101},(_,i)=>{const wavelength=(380+i*4)*1e-9;return 1/(wavelength**5*Math.expm1(.01438776877/(wavelength*target.temperature)));}),max=Math.max(...values);node.querySelector('#spectrum-line').setAttribute('d',values.map((v,i)=>(i?'L':'M')+(i*5)+','+(132-v/max*120).toFixed(2)).join(' '));node.querySelector('#record-spectrum').onclick=()=>{this.observe(target);this.x.closeDialog();};
 }
 journal(){const rows=this.entries.slice().reverse().map(e=>`<article class="journal-entry">${typeof e.photo==='string'&&/^data:image\/jpeg;base64,[A-Za-z0-9+/=]+$/.test(e.photo)?`<img src="${e.photo}" alt="Captura de la observación" loading="lazy">`:''}<div><h3>${escapeHTML(e.title)}</h3><small>${escapeHTML(e.date)} · ${e.destination==='moon'?'Luna':'Tierra'} · ciclo ${Number(e.hour).toFixed(2)} h</small><p>${escapeHTML(e.note)}</p></div></article>`).join('');const content=this.x.dialog('Cuaderno de observaciones',`<div class="science-heading-row"><span>${this.entries.length} registros</span><button id="export-field">Exportar expedición</button><label class="import-label">Importar <input id="import-field" type="file" accept=".json,application/json" hidden></label></div><label class="science-date">Fecha del catálogo planetario <input type="date" id="science-date" min="1800-01-01" max="2050-12-31" value="${this.x.env.celestial.date}"></label><p class="science-note">Planetas: aproximación JPL de la fecha elegida. El ciclo día/noche orienta el cielo del juego; no representa una ubicación geográfica real.</p><details><summary>Tu siguiente descubrimiento</summary><ul class="science-progress">${FILTERS.map(([id,name,goal])=>`<li>${this.unlocked.includes(id)?'✓':'○'} ${name}<small>${goal}</small></li>`).join('')}</ul></details><div class="journal-list">${rows||'<p class="empty-journal">Aún no hay observaciones. Selecciona el identificador, mira una estrella y mantén el botón de acción.</p>'}</div>`);
  content.querySelector('#export-field').onclick=()=>this.x.export();content.querySelector('#import-field').onchange=e=>this.x.import(e.target.files[0]);content.querySelector('#science-date').onchange=e=>{if(this.x.env.celestial.setDate(e.target.value))this.x.toast('Fecha planetaria actualizada.');else this.x.toast('Elige una fecha entre 1800 y 2050.');};
 }
 filters(){const content=this.x.dialog('Bandas de observación',`<p class="science-note">Fuera del visible, estas vistas son ilustraciones didácticas en falso color. No simulan un detector ni contienen datos IR, UV, radio, X o gamma del cielo.</p><div class="filter-options">${FILTERS.map(([id,name,goal])=>`<button data-filter="${id}" ${this.unlocked.includes(id)?'':'disabled'} aria-pressed="${this.filter===id}"><b>${name}</b><small>${this.unlocked.includes(id)?id==='visible'?'Color visible':'Representación en falso color':goal}</small></button>`).join('')}</div>`);
  content.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{if(b.dataset.filter!=='visible'&&!this.x.env.world.powered(this.x.seated.entity))return this.x.toast('Coloca un panel solar o módulo de energía a menos de 18 m.');this.filter=b.dataset.filter;this.x.renderer.domElement.dataset.filter=this.filter;this.x.filterLabel.textContent=this.filter==='visible'?'Visible':'Falso color · '+b.querySelector('b').textContent;this.x.closeDialog();});
 }
 lamp(entity){const content=this.x.dialog('Luz del puesto',`<p>Temperatura de color</p><div class="temperature-options">${LAMP_TEMPERATURES.map((t,i)=>`<button data-temperature="${i}" aria-pressed="${(entity.params.temperature||0)===i}"><span style="background:#${t.color.toString(16)}"></span>${t.label}</button>`).join('')}</div><button class="science-primary" id="toggle-lamp">${entity.params.on===false?'Encender':'Apagar'}</button>`);content.querySelectorAll('[data-temperature]').forEach(b=>b.onclick=()=>{this.x.env.world.change(entity,{temperature:Number(b.dataset.temperature)});this.x.tickSound();this.lamp(entity);});content.querySelector('#toggle-lamp').onclick=()=>{this.x.env.world.change(entity,{on:entity.params.on===false});this.x.tickSound();this.lamp(entity);};}
 analyze(entity){const world=this.x.env.world,inv=this.x.inventory;if(!world.powered(entity))return this.x.toast('La mesa necesita un panel solar o módulo de energía a menos de 18 m.');const sample=inv.count('regolith')?'regolith':inv.count('soil')?'soil':null;if(!sample)return this.x.dialog('Mesa de análisis','<p>Recoge primero una muestra mirando al suelo con el recolector. Después vuelve a esta mesa.</p>');const lunar=sample==='regolith';const note=lunar?'Modelo representativo: fragmentos minerales, roca y vidrio de impacto. Silicatos con oxígeno, silicio, aluminio, calcio, hierro y magnesio; composición variable según el lugar.':'Modelo representativo: partículas minerales, materia orgánica, poros con agua y aire. No corresponde a una medición de esta pradera.';const c=this.x.dialog('Análisis de muestra',`<p class="eyebrow">${ITEMS[sample].name}</p><p>${note}</p><p class="science-note">Ficha educativa representativa. No es una medición geológica del terreno procedural.</p><button id="analyze-sample" class="science-primary">Analizar una unidad y registrar</button>`);c.querySelector('button').onclick=()=>{if(inv.remove(sample,1)){this.record({id:sample,name:lunar?'Análisis de regolito':'Análisis de suelo'},'analysis',note);this.x.closeDialog();}};}
 beacon(entity){const c=this.x.dialog('Nombrar baliza','<label>Nombre <input id="beacon-name" maxlength="32" placeholder="Base, Observatorio, Cráter…"></label><button class="science-primary">Guardar nombre</button>');c.querySelector('input').value=entity.params.name||'Baliza';c.querySelector('button').onclick=()=>{this.x.env.world.change(entity,{name:c.querySelector('input').value.trim().slice(0,32)||'Baliza'});this.x.closeDialog();};}
 storage(entity){entity.params.storage ||= [];const slots=entity.params.storage;const content=this.x.dialog('Caja de campo',`<p>Deposita la casilla seleccionada de acceso rápido. Toca un stack para devolverlo a tu mochila.</p><div class="storage-grid">${Array.from({length:10},(_,i)=>`<button data-storage="${i}">${slots[i]?itemIcon(slots[i].id)+`<span>${escapeHTML(ITEMS[slots[i].id]?.name)} ×${slots[i].qty}</span>`:'Vacío'}</button>`).join('')}</div><button id="store-selected" class="science-primary">Depositar casilla seleccionada</button>`);
  content.querySelectorAll('[data-storage]').forEach(b=>b.onclick=()=>{const index=Number(b.dataset.storage),s=slots[index];if(!s)return;const left=this.x.inventory.add(s.id,s.qty);slots[index]=left?{id:s.id,qty:left}:null;this.x.env.world.change(entity,{storage:slots});this.storage(entity);});content.querySelector('#store-selected').onclick=()=>{const inv=this.x.inventory,s=inv.hand;if(!s)return this.x.toast('Selecciona antes un objeto de acceso rápido.');let remaining=s.qty;for(let i=0;i<10&&remaining;i++)if(slots[i]?.id===s.id){const add=Math.min(30-slots[i].qty,remaining);slots[i].qty+=add;remaining-=add;}for(let i=0;i<10&&remaining;i++)if(!slots[i]){slots[i]={id:s.id,qty:remaining};remaining=0;}if(remaining===s.qty)return this.x.toast('La caja está llena.');inv.consume(30+inv.selected,s.qty-remaining);this.x.env.world.change(entity,{storage:slots});this.storage(entity);};
 }
 seismometer(){const lunar=this.x.state.destination==='moon',c=this.x.dialog('Sismómetro',`<p class="eyebrow">${lunar?'Registro lunar':'Registro de suelo'} · SIMULACIÓN</p><svg class="seismogram" viewBox="0 0 500 120" role="img" aria-label="Señal sísmica simulada"><path fill="none" stroke="#8fc2b4" stroke-width="1.8"/></svg><p>Señales periódicas ilustrativas ${lunar?'de vibración lunar':'del terreno'}. La gráfica no representa datos de un sensor real.</p><button class="science-primary">Guardar registro</button>`);this.tick=t=>{const points=[];for(let i=0;i<200;i++){const tt=t-i*.038,phase=((tt%18)+18)%18,amplitude=phase<3?Math.exp(-phase)*35:1.8;points.push((i?'L':'M')+(500-i*2.5)+','+(60+Math.sin(tt*47)*amplitude+Math.sin(tt*73)*amplitude*.3).toFixed(2));}c.querySelector('path').setAttribute('d',points.join(' '));};c.querySelector('button').onclick=()=>this.record({id:'seismic-'+this.x.state.destination,name:lunar?'Vibración lunar simulada':'Vibración de suelo simulada'},'seismic','Registro ilustrativo, no medición real.');}
 weather(){const lunar=this.x.state.destination==='moon',hour=this.x.state.hour,temp=17+8*Math.sin((hour-9)/24*Math.PI*2),wind=2.6+1.3*Math.sin(hour*.7);this.x.dialog('Estación meteorológica',lunar?'<p>En este entorno lunar no hay atmósfera que produzca viento o clima terrestre. Usa esta estación en la pradera.</p>':`<p class="eyebrow">MODELO AMBIENTAL SIMULADO</p><div class="science-stat">${temp.toFixed(1)} <small>°C</small></div><p>Viento simulado: ${wind.toFixed(1)} m/s · Iluminación: ${Math.round(this.x.env.sky.day*100)} %</p><p class="science-note">Valores didácticos vinculados al ciclo del juego; no son un pronóstico meteorológico.</p>`);}
 radio(entity){if(!this.x.env.world.powered(entity))return this.x.toast('La antena necesita un panel solar o módulo de energía a menos de 18 m.');const c=this.x.dialog('Escuchar el cielo','<p class="eyebrow">RECEPTOR DIDÁCTICO · SEÑALES SINTETIZADAS</p><div class="radio-dial"><i></i></div><label>Frecuencia <output id="radio-frequency"></output><input id="radio-tune" type="range" min="1" max="5.3" step="0.002" value="1.505"></label><p id="radio-signal">Ruido de fondo</p><p class="science-note">Explora cerca de 32 MHz, 400 MHz y 160 GHz. Son ejemplos sonoros, no emisiones recibidas ni mediciones del cielo.</p>');const slider=c.querySelector('input'),stations=[{log:Math.log10(32),name:'Ruido solar',frequency:140},{log:Math.log10(400),name:'Púlsar ilustrativo',frequency:220},{log:Math.log10(160000),name:'Fondo cósmico ilustrativo',frequency:85}];let station=null,locked=0,recorded=null;
  const audio=this.x.env.audio,ctx=audio.ctx;let oscillator,gain,noise,noiseGain;if(ctx){oscillator=ctx.createOscillator();gain=ctx.createGain();oscillator.type='sine';gain.gain.value=0;oscillator.connect(gain);gain.connect(audio.master);oscillator.start();noise=ctx.createBufferSource();noise.buffer=audio.stepBuffer;noise.loop=true;noiseGain=ctx.createGain();noiseGain.gain.value=.025;const filter=ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=500;noise.connect(filter);filter.connect(noiseGain);noiseGain.connect(audio.master);noise.start();this.stopSound=()=>{gain.gain.setTargetAtTime(0,ctx.currentTime,.04);noiseGain.gain.setTargetAtTime(0,ctx.currentTime,.04);oscillator.stop(ctx.currentTime+.2);noise.stop(ctx.currentTime+.2);oscillator.onended=()=>{oscillator.disconnect();gain.disconnect();noise.disconnect();filter.disconnect();noiseGain.disconnect();};};}
  const tune=()=>{const value=Number(slider.value),mhz=10**value;station=stations.find(s=>Math.abs(s.log-value)<.035);locked=0;c.querySelector('output').textContent=mhz>=1000?(mhz/1000).toFixed(2)+' GHz':mhz.toFixed(2)+' MHz';c.querySelector('i').style.transform=`rotate(${(value-1)/4.3*270-135}deg)`;c.querySelector('#radio-signal').textContent=station?station.name+' · sincronizando':'Ruido de fondo';};slider.oninput=tune;tune();let last=0;
  this.tick=t=>{const dt=Math.min(.2,t-last);last=t;if(station){locked+=dt;if(locked>1.1&&recorded!==station.name){recorded=station.name;this.record({id:'radio-'+station.name,name:station.name},'radio','Señal sintetizada del receptor didáctico.');c.querySelector('#radio-signal').textContent=station.name+' · registrada';}}if(ctx){oscillator.frequency.setTargetAtTime(station?.frequency||80,ctx.currentTime,.06);gain.gain.setTargetAtTime(station?(station.name.startsWith('Púlsar')?(Math.sin(t*9)>.7?.12:.009):.045):0,ctx.currentTime,.035);noiseGain.gain.setTargetAtTime(station?.name.startsWith('Púlsar') ? .009 : station ? .04 : .025,ctx.currentTime,.08);}};
 }
 photo(target){const x=this.x;let photo=null;try{x.renderer.render(x.env.scene,x.camera);const c=document.createElement('canvas');c.width=300;c.height=180;c.getContext('2d').drawImage(x.renderer.domElement,0,0,300,180);photo=c.toDataURL('image/jpeg',.65);}catch{}this.record(target||{id:'landscape',name:'Paisaje de '+(x.state.destination==='moon'?'la Luna':'la Tierra'),kind:'photo'},target?.kind||'photo','Captura del entorno de la expedición.',photo);x.tickSound();}
}
